#!/bin/bash

set -eo pipefail

# Get the commit message of the latest commit in the current branch
commit_message=$(git log --format=%B -n 1)

# Check if the commit message contains the string "BUILD_CONTAINER_IMAGE"
if [[ $commit_message != *"BUILD_CONTAINER_IMAGE"* ]]; then
  echo "Commit message does not contain 'BUILD_CONTAINER_IMAGE'. Skipping container image build."
  exit 0
fi
