name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Include Check Commit Message workflow
        uses: ./.github/actions/check-commit-message.yaml

      - name: Include Check Pull Request Merged workflow
        uses: ./.github/actions/check-pull-req.yaml

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ajinkyak423/assignment:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ajinkyak423/assignment:latest
