name: Build Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - closed

jobs:
  build-on-push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.event.head_commit.message, 'BUILD_CONTAINER_IMAGE')

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ajinkyak423/assignment:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ajinkyak423/assignment:latest

  build-on-merged-pull-request:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request' && github.event.pull_request.merged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ajinkyak423/assignment:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ajinkyak423/assignment:latest
